language: go

go:
  - 1.6

services:
  - docker

before_install:
  - curl https://glide.sh/get | sh
  - glide install

script:
  - go test -v $(glide novendor)

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - make push-docker